mutation CreateMessage($message: String!) {
  createMessage(message: $message) {
    _id
    message
  }
}

mutation DeleteMessage($id: String!) {
  deleteMessage(id: $id)
}

query GetMessage($id: String!) {
	getMessage(id: $id) {
		message
	}
}